name=whmcloudflare
service=whostmgr
url=/cgi/whmcloudflare/whmcloudflare.cgi
url2=/cgi/whmcloudflare/index.php
entryurl=whmcloudflare/whmcloudflare.cgi
displayname=WHMCloudFlare
acls=all
user=root
target=_self
searchtext=WHMCloudFlare Cloudflare DNS
